Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,33 +8,33 @@ variables:
   DOCKER_SERVICE: "sanbe-hrms"
   RESTART_FLAG: "/tmp/restart_docker.lock"
 
-image: alpine:latest
-
-before_script:
-  - apk add --no-cache openssh-client curl wget
-  - eval $(ssh-agent -s)
-  - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-  - chmod 600 /tmp/deploy_key
-  - ssh-add /tmp/deploy_key
-  - mkdir -p ~/.ssh
-  - chmod 700 ~/.ssh
-  - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-  - mkdir -p /tmp/scripts
-  - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-  - |
-    if [ -f "/tmp/scripts/send_notification.sh" ]; then
-    echo "File successfully copied."
-    chmod +x /tmp/scripts/send_notification.sh
-    dos2unix /tmp/scripts/send_notification.sh
-    else
-    echo "Error: /tmp/scripts/send_notification.sh not found!"
-    exit 1
-    fi
-
 update_project:
   stage: build
   tags:
     - test4
+  image: alpine:latest
+  before_script:
+    - echo "Deploying latest updates via SSH..."
+    - apk add --no-cache openssh-client curl wget
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
+    - echo "$SSH_PRIVATE_KEY"
+    - chmod 600 /tmp/deploy_key
+    - ssh-add /tmp/deploy_key
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
+    - mkdir -p /tmp/scripts
+    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
+    - |
+      if [ -f "/tmp/scripts/send_notification.sh" ]; then
+      echo "File successfully copied."
+      chmod +x /tmp/scripts/send_notification.sh
+      dos2unix /tmp/scripts/send_notification.sh
+      else
+      echo "Error: /tmp/scripts/send_notification.sh not found!"
+      exit 1
+      fi
   script:
     - echo "Deploying latest updates via SSH..."
     - |
