[FIX] update gitlab-ci to automate deployment in prod

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,46 +4,64 @@ stages:
   - notify
 
 variables:
-  PROJECT_DIR: "/opt/docker-odoo-sanbe/docker-odoo-131/develop/customize/sanbe-hrms/"
-  DOCKER_SERVICE: "sanbe-hrms"
   RESTART_FLAG: "/tmp/restart_docker.lock"
+  # STAGING
+  PROJECT_DIR_STAGING: "/opt/docker-odoo-sanbe/docker-odoo-131/develop/customize/sanbe-hrms"
+  DOCKER_SERVICE_STAGING: "sanbe-hrms"
+  BRANCH_STAGING: "staging"
+  # PRODUCTION
+  PROJECT_DIR_PROD: "/home/albert/my-docker/docker-sanbe-hrms/customize/sanbe-hrms/"
+  APP_SERVICE_PROD: "OdooSanbe.service"
+  BRANCH_PROD: "production"
 
 image: alpine:latest
 
-before_script:
-  - apk add --no-cache openssh-client curl wget
-  - eval $(ssh-agent -s)
-  - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-  - chmod 600 /tmp/deploy_key
-  - ssh-add /tmp/deploy_key
-  - mkdir -p ~/.ssh
-  - chmod 700 ~/.ssh
-  - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-  - mkdir -p /tmp/scripts
-  - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-  - |
-    if [ -f "/tmp/scripts/send_notification.sh" ]; then
-      echo "File successfully copied."
-      chmod +x /tmp/scripts/send_notification.sh
-      dos2unix /tmp/scripts/send_notification.sh
-    else
-      echo "Error /tmp/scripts/send_notification.sh not found!"
-      exit 1
-    fi
-update_project:
+.default_before_script: &default_before_script
+  before_script:
+    - apk add --no-cache openssh-client curl wget jq dos2unix bash tzdata
+    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
+    - chmod 600 /tmp/deploy_key
+    - ssh-add /tmp/deploy_key
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - ssh-keyscan -H ${DEPLOY_SERVER_STAGING} >> ~/.ssh/known_hosts
+    - ssh-keyscan -H ${DEPLOY_SERVER_PROD:-$DEPLOY_SERVER} >> ~/.ssh/known_hosts    - mkdir -p /tmp/scripts
+    - |
+      scp -o StrictHostKeyChecking=no ${SSH_USER_PROD:-$SSH_USER}@${DEPLOY_SERVER_PROD:-$DEPLOY_SERVER}:/home/albert/script/send_notification.sh /tmp/scripts/
+      if [ -f "/tmp/scripts/send_notification.sh" ]; then
+        echo "✅ File successfully copied."
+        dos2unix /tmp/scripts/send_notification.sh
+        tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
+        mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
+        chmod +x /tmp/scripts/send_notification.sh
+      else
+        echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
+        exit 1
+      fi
+
+.default_prod_rule: &default_prod_rule
+  - if: '$CI_COMMIT_BRANCH == $BRANCH_PROD'
+
+.default_staging_rule: &default_staging_rule
+  - if: '$CI_COMMIT_BRANCH == $BRANCH_STAGING'
+
+# STAGING
+update_project_staging:
   stage: build
-  tags:
-    - test4
+  tags: [test4]
+  <<: *default_before_script
   script:
     - echo "Deploying latest updates via SSH..."
     - |
-      ssh -i /tmp/deploy_key $SSH_USER@$DEPLOY_SERVER <<EOF
-      if [ -d "$PROJECT_DIR" ]; then
+      ssh -i /tmp/deploy_key $SSH_USER_STAGING@$DEPLOY_SERVER_STAGING <<EOF
+      if [ -d "$PROJECT_DIR_STAGING" ]; then
         echo "Project directory exists. Pulling latest changes...";
-        cd "$PROJECT_DIR" && git pull origin staging
+        cd "$PROJECT_DIR_STAGING" && git pull origin $BRANCH_STAGING
         if [ $? -ne 0 ]; then
           git merge --abort
-          echo "Error: Failed to pull from origin/main"
+          echo "Error: Failed to pull from origin/$BRANCH_STAGING"
           exit 1
         fi
         echo "Success: Pulled latest project version";
@@ -54,250 +72,95 @@ update_project:
       fi
       EOF
   rules:
-    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging"'
+    - if: '$CI_COMMIT_BRANCH == $BRANCH_STAGING'
+      when: always
 
-restart_apps_scheduled:
+restart_staging:
   stage: deploy
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache openssh-client curl wget
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - echo "Checking SSH_PRIVATE_KEY length= $SSH_PRIVATE_KEY"
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-      echo "File successfully copied."
-      chmod +x /tmp/scripts/send_notification.sh
-      dos2unix /tmp/scripts/send_notification.sh
-      else
-      echo "Error: /tmp/scripts/send_notification.sh not found!"
-      exit 1
-      fi
+  tags: [test4]
+  <<: *default_before_script
   script:
-    - echo "running scheduled restart!"
-    - |
-      ssh -i /tmp/deploy_key $SSH_USER@$DEPLOY_SERVER "
-      if [ -d '$PROJECT_DIR' ]; then
-        echo 'Restarting Application...';
-        docker container restart "$DOCKER_SERVICE"
-        if [ $? -ne 0 ]; then # Check the exit code of the git pull command
-          echo 'Error: Application Restart Failed!'
-          exit 1
-        fi
-        echo 'Application Restarted Successfully!';
-      else
-        echo 'Error: Project directory does not exist!';
-        exit 1;
-      fi
+    - ssh -i /tmp/deploy_key $SSH_USER_STAGING@$DEPLOY_SERVER_STAGING "
+      docker container restart $DOCKER_SERVICE_STAGING
       "
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "staging"'
+  rules: *default_staging_rule
 
-success_notif_scheduled:
+notify_staging_success:
   stage: notify
-  image: alpine:latest
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache tzdata # Add this line
-    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime # Set the timezone
-    - apk add --no-cache curl wget jq dos2unix bash openssh-client
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "File successfully copied."
-        chmod +x /tmp/scripts/send_notification.sh
-        dos2unix /tmp/scripts/send_notification.sh
-      else
-        echo "Error: /tmp/scripts/send_notification.sh not found!"
-        exit 1
-      fi
+  tags: [test4]
+  <<: *default_before_script
   script:
-    - echo "Executing notification script..."
-    - TZ="Asia/Jakarta" /tmp/scripts/send_notification.sh "✅ Deployment Successful!" "Success" 3066993 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "staging"'
-  needs:
-    - job: restart_apps_scheduled
-      optional: false # Ensures this notification only runs if the manual deployment runs
+    - /tmp/scripts/send_notification.sh "✅ Staging Deployment Successful!" "Success" 3066993 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
+  rules: *default_staging_rule
   when: on_success
+  needs: [restart_staging]
 
-failure_notification_scheduled:
+notify_staging_failed:
   stage: notify
-  image: alpine:latest
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache curl wget jq dos2unix bash openssh-client
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "File successfully copied."
-        chmod +x /tmp/scripts/send_notification.sh
-        dos2unix /tmp/scripts/send_notification.sh
-      else
-        echo "Error: /tmp/scripts/send_notification.sh not found!"
-        exit 1
-      fi
+  tags: [test4]
+  <<: *default_before_script
   script:
-    - echo "Executing notification script..."
-    - TZ="Asia/Jakarta" /tmp/scripts/send_notification.sh "❌ Deployment Failed!" "Failed" 15552000 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "staging"'
-  needs:
-    - job: restart_apps_scheduled
-      optional: false # Ensures this notification only runs if the manual deployment runs
+    - /tmp/scripts/send_notification.sh "❌ Staging Deployment Failed!" "Error" 15158332 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
+  rules: *default_staging_rule
   when: on_failure
+  needs: [update_project_staging, restart_staging]
+# END STAGING
 
-restart_apps_manual:
-  stage: deploy
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache tzdata # Add this line
-    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime # Set the timezone
-    - apk add --no-cache openssh-client curl wget dos2unix bash
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "✅ File successfully copied."
-        chmod +x /tmp/scripts/send_notification.sh
-        dos2unix /tmp/scripts/send_notification.sh
-        tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
-        mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
-        chmod +x /tmp/scripts/send_notification.sh
-      else
-        echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
-        exit 1
-      fi
+# PRODUCTION
+update_project_production:
+  stage: build
+  tags: [test4]
+  <<: *default_before_script
   script:
-    - echo "🚀 Running urgent restart!"
-    - echo "📌 Webhook URL= $WEBHOOK_URL"
+    - echo "Deploying latest updates via SSH..."
     - |
-      ssh -i /tmp/deploy_key $SSH_USER@$DEPLOY_SERVER "
-      if [ -d '$PROJECT_DIR' ]; then
-        echo '🔄 Restarting Application...';
-        docker container restart \"$DOCKER_SERVICE\"
+      ssh -i /tmp/deploy_key $SSH_USER_PROD@$DEPLOY_SERVER_PROD <<EOF
+      if [ -d "$PROJECT_DIR_PROD" ]; then
+        echo "Project directory exists. Pulling latest changes...";
+        cd "$PROJECT_DIR_PROD" && git pull origin $BRANCH_PROD
         if [ $? -ne 0 ]; then
-          echo '❌ Error: Application Restart Failed!';
+          git merge --abort
+          echo "Error: Failed to pull from origin/$BRANCH_PROD"
           exit 1
         fi
-        echo '✅ Application Restarted Successfully!';
+        echo "Success: Pulled latest project version";
+        echo "$(date +%s)" > "$RESTART_FLAG"
       else
-        echo '❌ Error: Project directory does not exist!';
-        exit 1;
-      fi
-      "
-  only:
-    - staging
-  when: manual
-
-success_notif_manual:
-  stage: notify
-  image: alpine:latest
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache tzdata # Add this line
-    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime # Set the timezone
-    - apk add --no-cache curl wget jq dos2unix bash openssh-client
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "✅ File successfully copied."
-        chmod +x /tmp/scripts/send_notification.sh
-        dos2unix /tmp/scripts/send_notification.sh
-        tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
-        mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
-        chmod +x /tmp/scripts/send_notification.sh
-      else
-        echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
+        echo "Error: Project directory does not exist!"
         exit 1
       fi
-  script:
-    - echo "📢 Sending notification to Discord..."
-    - ls -lah /tmp/scripts/
-    - cat -A /tmp/scripts/send_notification.sh # Debug script content
-    - TZ="Asia/Jakarta" /tmp/scripts/send_notification.sh "✅ Manual Deployment Successful!" "Success" 3066993 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
-  needs:
-    - job: restart_apps_manual
-      optional: false # Ensures this notification only runs if the manual deployment runs
-  only:
-    - staging
-  when: on_success
-
-failure_notification_manual:
-  stage: notify
-  image: alpine:latest
-  tags:
-    - test4
-  before_script:
-    - apk add --no-cache tzdata # Add this line
-    - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime # Set the timezone
-    - apk add --no-cache curl wget jq dos2unix bash openssh-client
-    - eval $(ssh-agent -s)
-    - echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
-    - chmod 600 /tmp/deploy_key
-    - ssh-add /tmp/deploy_key
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
-    - mkdir -p /tmp/scripts
-    - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
-    - |
-      if [ -f "/tmp/scripts/send_notification.sh" ]; then
-        echo "File successfully copied."
-        chmod +x /tmp/scripts/send_notification.sh
-        dos2unix /tmp/scripts/send_notification.sh
-      else
-        echo "Error: /tmp/scripts/send_notification.sh not found!"
-        exit 1
-      fi
-  script:
-    - echo "Executing notification script..."
-    - /tmp/scripts/send_notification.sh "❌ Deployment Failed!" "Failed" 15552000 "SANBE HRMS - STAGING" "$WEBHOOK_URL"
+      EOF
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main"'
-  dependencies:
-    - restart_apps_scheduled
+    - if: '$CI_COMMIT_BRANCH == $BRANCH_PROD'
+      when: always
+
+restart_production:
+  stage: deploy
+  tags: [test4]
+  <<: *default_before_script
+  script:
+    - ssh -i /tmp/deploy_key $SSH_USER_PROD@$DEPLOY_SERVER_PROD "
+      sudo systemctl restart $APP_SERVICE_PROD
+      "
+  rules: *default_prod_rule
+
+notify_production_success:
+  stage: notify
+  tags: [test4]
+  <<: *default_before_script
+  script:
+    - /tmp/scripts/send_notification.sh "✅ Production Deployment Successful!" "Success" 3066993 "SANBE HRMS - $BRANCH_PROD" "$WEBHOOK_URL"
+  rules: *default_prod_rule
+  when: on_success
+  needs: [restart_production]
+
+notify_production_failed:
+  stage: notify
+  tags: [test4]
+  <<: *default_before_script
+  script:
+    - /tmp/scripts/send_notification.sh "❌ Production Deployment Failed!" "Error" 15158332 "SANBE HRMS - PRODUCTION" "$WEBHOOK_URL"
+  rules: *default_prod_rule
   when: on_failure
+  needs: [update_project_production, restart_production]
+# END PRODUCTION
