update gitlab-ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,14 +23,13 @@ before_script:
   - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
   - |
     if [ -f "/tmp/scripts/send_notification.sh" ]; then
-    echo "File successfully copied."
-    chmod +x /tmp/scripts/send_notification.sh
-    dos2unix /tmp/scripts/send_notification.sh
+      echo "File successfully copied."
+      chmod +x /tmp/scripts/send_notification.sh
+      dos2unix /tmp/scripts/send_notification.sh
     else
-    echo "Error: /tmp/scripts/send_notification.sh not found!"
-    exit 1
+      echo "Error /tmp/scripts/send_notification.sh not found!"
+      exit 1
     fi
-
 update_project:
   stage: build
   tags:
@@ -38,23 +37,24 @@ update_project:
   script:
     - echo "Deploying latest updates via SSH..."
     - |
-      ssh -i /tmp/deploy_key $SSH_USER@$DEPLOY_SERVER "
-      if [ -d '$PROJECT_DIR' ]; then
-        echo 'Project directory exists. Pulling latest changes...';
-        cd '$PROJECT_DIR' && git pull origin staging
-        if [ $? -ne 0 ]; then # Check the exit code of the git pull command
-          echo 'Error: Failed to pull from origin/staging'
+      ssh -i /tmp/deploy_key $SSH_USER@$DEPLOY_SERVER <<EOF
+      if [ -d "$PROJECT_DIR" ]; then
+        echo "Project directory exists. Pulling latest changes...";
+        cd "$PROJECT_DIR" && git pull origin staging
+        if [ $? -ne 0 ]; then
+          git merge --abort
+          echo "Error: Failed to pull from origin/main"
           exit 1
         fi
-        echo 'Success to pull newest project';
-        echo '$(date +%s)' > '$RESTART_FLAG';
+        echo "Success: Pulled latest project version";
+        echo "$(date +%s)" > "$RESTART_FLAG"
       else
-        echo 'Error: Project directory does not exist!';
-        exit 1;
+        echo "Error: Project directory does not exist!"
+        exit 1
       fi
-      "
-  only:
-    - staging
+      EOF
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging"'
 
 restart_apps_scheduled:
   stage: deploy
