Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,11 +11,11 @@ variables:
 image: alpine:latest
 
 before_script:
-  - apk add --no-cache openssh-client curl wget tzdata dos2unix bash
-  - ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
+  - apk add --no-cache openssh-client curl wget
   - eval $(ssh-agent -s)
   - chmod 600 /tmp/deploy_key
   - ssh-add /tmp/deploy_key
+  - ssh-keygen -lf /tmp/deploy_key
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
@@ -23,15 +23,12 @@ before_script:
   - scp -o StrictHostKeyChecking=no $SSH_USER@$DEPLOY_SERVER:/home/albert/script/send_notification.sh /tmp/scripts/
   - |
     if [ -f "/tmp/scripts/send_notification.sh" ]; then
-      echo "✅ File successfully copied."
-      chmod +x /tmp/scripts/send_notification.sh
-      dos2unix /tmp/scripts/send_notification.sh
-      tr -d '\r' < /tmp/scripts/send_notification.sh > /tmp/scripts/send_notification_fixed.sh
-      mv /tmp/scripts/send_notification_fixed.sh /tmp/scripts/send_notification.sh
-      chmod +x /tmp/scripts/send_notification.sh
+    echo "File successfully copied."
+    chmod +x /tmp/scripts/send_notification.sh
+    dos2unix /tmp/scripts/send_notification.sh
     else
-      echo "❌ Error: /tmp/scripts/send_notification.sh not found!"
-      exit 1
+    echo "Error: /tmp/scripts/send_notification.sh not found!"
+    exit 1
     fi
 
 update_project:
